-- 0003_auth_tables — Phase 4 stage A: Better Auth core schema reconciliation
-- (docs/data-model.md §1, ADR-0002, ADR-0007).
--
-- Purpose: create the four Better Auth core tables that Phase 3 deferred
-- (auth_accounts, auth_sessions, auth_verifications) plus the database-
-- storage rate-limit table (auth_rate_limits, ADR-0002 — in-memory rate
-- limiting is unusable on Workers), and extend `users` with the one Better
-- Auth core column the Phase 3 placeholder was missing (`image`).
--
-- Additive only: every statement is CREATE TABLE / CREATE INDEX / ALTER
-- TABLE ... ADD COLUMN. Nothing is dropped, retyped, or backfilled.
-- `email_verified`/`created_at`/`updated_at` on `users` and the new tables'
-- timestamp columns keep their existing SQLite INTEGER storage — Better
-- Auth's Drizzle adapter maps JS `Date`/`boolean` to/from that INTEGER on
-- the application side (packages/db/src/schema/identity.ts DEVIATION
-- comment); no DDL change was needed for that mapping.
--
-- Generated by drizzle-kit (0.31.x) from packages/db/src/schema/index.ts
-- (baseline snapshot re-derived from the Phase 3 schema, diffed against the
-- Phase 4 schema — see procedure note in the ledger), then flattened to
-- wrangler's migration format (statement-breakpoints stripped). Date:
-- 2026-08-14. 0001_init and 0002_core_schema are untouched.
CREATE TABLE `auth_accounts` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`account_id` text NOT NULL,
	`provider_id` text NOT NULL,
	`access_token` text,
	`refresh_token` text,
	`access_token_expires_at` integer,
	`refresh_token_expires_at` integer,
	`scope` text,
	`id_token` text,
	`password` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE INDEX `idx_auth_accounts__user_id` ON `auth_accounts` (`user_id`);
CREATE TABLE `auth_rate_limits` (
	`id` text PRIMARY KEY NOT NULL,
	`key` text NOT NULL,
	`count` integer NOT NULL,
	`last_request` integer NOT NULL
);

CREATE UNIQUE INDEX `uq_auth_rate_limits__key` ON `auth_rate_limits` (`key`);
CREATE TABLE `auth_sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`token` text NOT NULL,
	`expires_at` integer NOT NULL,
	`ip_address` text,
	`user_agent` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE UNIQUE INDEX `uq_auth_sessions__token` ON `auth_sessions` (`token`);
CREATE INDEX `idx_auth_sessions__user_id` ON `auth_sessions` (`user_id`);
CREATE TABLE `auth_verifications` (
	`id` text PRIMARY KEY NOT NULL,
	`identifier` text NOT NULL,
	`value` text NOT NULL,
	`expires_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);

CREATE INDEX `idx_auth_verifications__identifier` ON `auth_verifications` (`identifier`);
ALTER TABLE `users` ADD `image` text;
