-- 0005_nullable_authorship — Phase 11 stage A: privacy reconciliation
-- (docs/privacy.md commitment 1, self-service account deletion).
--
-- Purpose: relaxes `saved_tenders.saved_by_user_id`,
-- `ignored_tenders.ignored_by_user_id`, and `customer_feedback.user_id`
-- from NOT NULL to NULLable.
--
-- Why: these three rows are ORG data (a saved tender/ignore/feedback row
-- stays useful to every member of the org, not just its author) — the FK to
-- `users` is an attribution field only. Before this migration, a non-owner
-- MEMBER who authored one of these rows and then deleted their own account
-- (apps/worker/src/routes/account.ts: memberships are removed, then Better
-- Auth's `deleteUser` runs) would hit a foreign-key violation, because D1
-- runs with `PRAGMA foreign_keys=ON` and these three columns still
-- referenced the about-to-be-deleted `users` row with no compensating
-- update. Account deletion now SET NULLs the departing user's authored rows
-- in every org they remain a member of, before calling `deleteUser` — the
-- same "anonymize the author, keep the row" pattern already used for
-- `audit_events.actor_id`. See packages/db/src/schema/engagement.ts's
-- module doc for the full rationale.
--
-- SQLite has no `ALTER TABLE ... ALTER COLUMN`, so relaxing a NOT NULL
-- constraint requires the create-new / copy / swap table-rebuild pattern
-- (migration-safety skill). No data is lost: every existing row's
-- non-null author value is copied across unchanged; only future writes may
-- leave these columns null (Better Auth account deletion only).
--
-- Generated by drizzle-kit (0.31.x) from packages/db/src/schema/
-- engagement.ts (packages/db/drizzle/0002_nullable_authorship.sql),
-- flattened to wrangler's migration format (statement-breakpoints
-- stripped) — byte-identical statements, reordered only to keep each
-- table's create/copy/drop/rename/index block together. `drizzle-kit
-- generate` after this change produces a ZERO diff (schema <-> SQL
-- agreement proven).
-- Date: 2026-08-15.
PRAGMA foreign_keys=OFF;

CREATE TABLE `__new_customer_feedback` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`match_id` text NOT NULL,
	`user_id` text,
	`verdict` text NOT NULL,
	`reasons_json` text,
	`comment` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`match_id`) REFERENCES `tender_matches`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "ck_customer_feedback__verdict" CHECK("__new_customer_feedback"."verdict" IN ('useful', 'not_useful'))
);

INSERT INTO `__new_customer_feedback`("id", "organization_id", "match_id", "user_id", "verdict", "reasons_json", "comment", "created_at", "updated_at") SELECT "id", "organization_id", "match_id", "user_id", "verdict", "reasons_json", "comment", "created_at", "updated_at" FROM `customer_feedback`;
DROP TABLE `customer_feedback`;
ALTER TABLE `__new_customer_feedback` RENAME TO `customer_feedback`;

CREATE UNIQUE INDEX `uq_customer_feedback__organization_id_match_id` ON `customer_feedback` (`organization_id`,`match_id`);
CREATE INDEX `idx_customer_feedback__organization_id_created_at` ON `customer_feedback` (`organization_id`,`created_at`);

CREATE TABLE `__new_ignored_tenders` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`lot_id` text NOT NULL,
	`notice_id` text NOT NULL,
	`ignored_by_user_id` text,
	`reason` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`lot_id`) REFERENCES `tender_lots`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`notice_id`) REFERENCES `tender_notices`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`ignored_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);

INSERT INTO `__new_ignored_tenders`("id", "organization_id", "lot_id", "notice_id", "ignored_by_user_id", "reason", "created_at") SELECT "id", "organization_id", "lot_id", "notice_id", "ignored_by_user_id", "reason", "created_at" FROM `ignored_tenders`;
DROP TABLE `ignored_tenders`;
ALTER TABLE `__new_ignored_tenders` RENAME TO `ignored_tenders`;

CREATE UNIQUE INDEX `uq_ignored_tenders__organization_id_lot_id` ON `ignored_tenders` (`organization_id`,`lot_id`);
CREATE INDEX `idx_ignored_tenders__lot_id` ON `ignored_tenders` (`lot_id`);

CREATE TABLE `__new_saved_tenders` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`lot_id` text NOT NULL,
	`notice_id` text NOT NULL,
	`saved_by_user_id` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`lot_id`) REFERENCES `tender_lots`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`notice_id`) REFERENCES `tender_notices`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`saved_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);

INSERT INTO `__new_saved_tenders`("id", "organization_id", "lot_id", "notice_id", "saved_by_user_id", "created_at") SELECT "id", "organization_id", "lot_id", "notice_id", "saved_by_user_id", "created_at" FROM `saved_tenders`;
DROP TABLE `saved_tenders`;
ALTER TABLE `__new_saved_tenders` RENAME TO `saved_tenders`;

CREATE UNIQUE INDEX `uq_saved_tenders__organization_id_lot_id` ON `saved_tenders` (`organization_id`,`lot_id`);
CREATE INDEX `idx_saved_tenders__lot_id` ON `saved_tenders` (`lot_id`);

PRAGMA foreign_keys=ON;
