-- 0006_org_created_by_nullable — Phase 11 stage A: privacy reconciliation
-- (docs/privacy.md commitment 1/2, discovered while testing migration
-- 0005's fix).
--
-- Purpose: relaxes `organizations.created_by_user_id` from NOT NULL to
-- NULLable.
--
-- Why: `organizations` rows are NEVER hard-deleted (a `deleted` org is kept
-- forever as a tombstone — `status` stays `deleted`, `name` becomes
-- `deleted-<id>`; see packages/db/src/repositories/identity.ts's
-- `tombstoneOrganization`). With `created_by_user_id` NOT NULL, the user who
-- created ANY org — even after that org is deleted and purged — could NEVER
-- delete their own account again: Better Auth's `deleteUser` would hit the
-- same `PRAGMA foreign_keys=ON` violation this whole migration set already
-- fixes for `saved_tenders`/`ignored_tenders`/`customer_feedback` (migration
-- 0005), just via a different table. Found by a D1 test exercising exactly
-- that path (a sole owner deletes their org, then their account).
--
-- `routes/account.ts` SET NULLs `organizations.created_by_user_id` for
-- every org the departing user created (regardless of that org's `status`)
-- immediately before removing memberships / calling `deleteUser` — the same
-- "anonymize the author, keep the row" pattern as migration 0005's three
-- columns and `audit_events.actor_id`.
--
-- SQLite has no `ALTER TABLE ... ALTER COLUMN`, so relaxing a NOT NULL
-- constraint requires the create-new / copy / swap table-rebuild pattern
-- (migration-safety skill). No data is lost: every existing row's non-null
-- `created_by_user_id` is copied across unchanged.
--
-- Generated by drizzle-kit (0.31.x) from packages/db/src/schema/
-- identity.ts (packages/db/drizzle/0003_org_created_by_nullable.sql),
-- flattened to wrangler's migration format (statement-breakpoints
-- stripped) — byte-identical statements. `drizzle-kit generate` after this
-- change produces a ZERO diff (schema <-> SQL agreement proven).
-- Date: 2026-08-15.
PRAGMA foreign_keys=OFF;

CREATE TABLE `__new_organizations` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`status` text NOT NULL,
	`created_by_user_id` text,
	`suspended_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`created_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "ck_organizations__status" CHECK("__new_organizations"."status" IN ('active', 'deleted'))
);

INSERT INTO `__new_organizations`("id", "name", "status", "created_by_user_id", "suspended_at", "created_at", "updated_at") SELECT "id", "name", "status", "created_by_user_id", "suspended_at", "created_at", "updated_at" FROM `organizations`;
DROP TABLE `organizations`;
ALTER TABLE `__new_organizations` RENAME TO `organizations`;

PRAGMA foreign_keys=ON;
