-- 0008_ingestion_fetch_retries — ADR-0008 §3/§5: per-notice XML fetch retry
-- queue (poison-pill resilience) + a run-level fetch-failure counter.
--
-- Purpose: `ingestion_fetch_retries` gives a skipped-per-notice XML fetch
-- failure (ADR-0008 §1 — a `TedRequestError` that used to be window-fatal)
-- a durable, bounded retry path. The checkpoint advances past a `partial`
-- window, so without this table a skipped notice would never be revisited.
-- A row is inserted, idempotently on `(source, source_notice_id)`, whenever
-- a notice is skipped; the daily ingestion cron drains due rows
-- (`status = 'pending' AND next_attempt_at <= now`, oldest first, capped at
-- `FETCH_RETRY_MAX_PER_RUN`) through the identical fetch/parse/persist path.
-- `ingestion_runs.notices_fetch_failed` is a run-level counter of those
-- skips so watchdog/admin queries need one indexed read instead of grouping
-- `ingestion_errors` by the `NOTICE_FETCH_` code prefix on every check.
--
-- Global operational table (no `organization_id`), consistent with the
-- other ingestion-ops tables in this file (`ingestion_checkpoints`,
-- `ingestion_errors`, `ingestion_runs`, `source_snapshots`) —
-- docs/security.md C6 exempts this class of table; see the module header
-- comment in packages/db/src/schema/ingestion.ts and
-- packages/db/src/repositories/ingestion.ts.
--
-- Index shape (`idx_ingestion_fetch_retries__pending_next_attempt_at`):
-- partial on `WHERE status = 'pending'`, columns `(next_attempt_at, id)`.
-- This is an exact match for the one query this table serves — the drain
-- query `WHERE status = 'pending' AND next_attempt_at <= ? ORDER BY
-- next_attempt_at ASC, id ASC LIMIT ?` (repositories/ingestion.ts
-- `listDueFetchRetries`). Partial because `recovered`/`abandoned` rows are
-- never read by that query and would otherwise sit in the index forever
-- between retention purges; leading `next_attempt_at` lets SQLite walk rows
-- already in the required order with no in-memory sort; trailing `id`
-- breaks ties deterministically ("oldest first") using the ULID's built-in
-- creation-time ordering, so no extra `created_at` column is needed in the
-- index. `uq_ingestion_fetch_retries__source_source_notice_id` is the
-- idempotency key an upsert-on-conflict write needs and must exist at
-- table-creation time (SQLite cannot add a UNIQUE constraint later without
-- a table rebuild — migration-safety skill).
--
-- Cost/size: ADR-0008 §3 projects worst-case ~0.33 MB/year of D1 growth
-- before retention purges terminal rows — negligible against the 10 GB D1
-- cap (ADR-0003 headroom rule, docs/cost-model.md).
--
-- Additive only: one CREATE TABLE, two CREATE INDEX, one ALTER TABLE ...
-- ADD COLUMN (with a DEFAULT, so the existing NOT NULL rule is satisfied
-- without a backfill or table rebuild). Nothing dropped/retyped — no data
-- is lost.
--
-- Generated by drizzle-kit (0.31.x) from packages/db/src/schema/
-- ingestion.ts (packages/db/drizzle/0005_ingestion_fetch_retries.sql),
-- flattened to wrangler's migration format (statement-breakpoints
-- stripped) — byte-identical statements. `drizzle-kit generate` after this
-- change produces a ZERO diff (schema <-> SQL agreement proven). Date:
-- 2026-08-19.
CREATE TABLE `ingestion_fetch_retries` (
	`id` text PRIMARY KEY NOT NULL,
	`source` text NOT NULL,
	`source_notice_id` text NOT NULL,
	`xml_url` text NOT NULL,
	`publication_date` text NOT NULL,
	`attempts` integer DEFAULT 0 NOT NULL,
	`next_attempt_at` integer NOT NULL,
	`last_error_code` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT "ck_ingestion_fetch_retries__status" CHECK("ingestion_fetch_retries"."status" IN ('pending', 'recovered', 'abandoned'))
);

CREATE UNIQUE INDEX `uq_ingestion_fetch_retries__source_source_notice_id` ON `ingestion_fetch_retries` (`source`,`source_notice_id`);
CREATE INDEX `idx_ingestion_fetch_retries__pending_next_attempt_at` ON `ingestion_fetch_retries` (`next_attempt_at`,`id`) WHERE "ingestion_fetch_retries"."status" = 'pending';
ALTER TABLE `ingestion_runs` ADD `notices_fetch_failed` integer DEFAULT 0 NOT NULL;
