/**
 * Writes the public sample-verdict demo's data file.
 *
 * All of the actual work — which notices, which profiles, and running the
 * production engine over them — lives in `src/sample-verdicts.ts`, so it is
 * covered by the normal test run. This script only reads fixtures off disk
 * and renders the module.
 *
 * Run (from packages/procurement, so workspace imports resolve):
 *   npx tsx scripts/generate-sample-verdicts.ts
 * Output: apps/web/src/lib/sample-verdicts.generated.ts (committed).
 *
 * `tests/integration/sample-verdicts-committed.test.ts` fails if the committed file does not
 * match a fresh build, so a forgotten regeneration is a red test rather than
 * a demo quietly showing numbers the engine no longer produces.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildSampleVerdicts } from '../src/sample-verdicts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');

const build = buildSampleVerdicts((relativePath) =>
  readFileSync(resolve(ROOT, 'tests/fixtures/ted', relativePath), 'utf8'),
);

for (const verdict of build.verdicts) {
  const rule = verdict.exclusionRule;
  console.log(
    `  ${String(verdict.id).padEnd(26)} ${String(verdict.score ?? '\u2014').padStart(5)}  ` +
      `${String(verdict.classification)}${rule !== null ? ` (${String(rule)}: ${String(verdict.exclusionEvidence)})` : ''}`,
  );
}

const output = `/* GENERATED by packages/procurement/scripts/generate-sample-verdicts.ts — do not edit by hand.
 *
 * Real output of the production matching engine (v${build.engineVersion}) scoring
 * real TED notices against representative supplier profiles, at a pinned
 * scoring time. Regenerate after any engine or fixture change; the committed
 * contents are checked against a fresh build by
 * tests/integration/sample-verdicts-committed.test.ts.
 */
import type { SampleVerdict } from './sample-verdicts';

export const SAMPLE_VERDICT_ENGINE_VERSION = '${build.engineVersion}';
export const SAMPLE_VERDICT_SCORED_AT = ${String(build.scoredAt)};

export const SAMPLE_VERDICTS: readonly SampleVerdict[] = ${JSON.stringify(build.verdicts, null, 2)};
`;

const outPath = resolve(ROOT, 'apps/web/src/lib/sample-verdicts.generated.ts');
writeFileSync(outPath, output);
console.log(`wrote ${String(build.verdicts.length)} verdicts to ${outPath}`);
