#!/usr/bin/env bash
# Containerized local dev entrypoint (docker-compose.yml / .devcontainer).
# Installs deps if missing, guarantees a local-only apps/worker/.dev.vars
# (never real credentials — HUMAN_DECISION_BLOCKERS items 3/4/5), applies
# D1 migrations to the local simulator, then runs BOTH dev servers:
#   :8787  wrangler dev  — API + (if built) the SPA assets
#   :5173  vite dev      — HMR frontend, /api proxied to :8787
# Everything is local/simulated; no Cloudflare login or network secrets.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# `-d node_modules` is useless as an install sentinel here: the compose
# named volume mounts an (initially empty) directory over it, so the dir
# always exists. Probe for an actually-usable install instead — wrangler
# resolvable from apps/worker via the linux-native store in the volume.
if ! (cd apps/worker && node -e 'require.resolve("wrangler/package.json")') >/dev/null 2>&1; then
  echo "[dev] installing dependencies..."
  pnpm install --frozen-lockfile
fi

if [ ! -f apps/worker/.dev.vars ]; then
  echo "[dev] generating local-only apps/worker/.dev.vars..."
  SECRET="$(node -e 'console.log(require("node:crypto").randomBytes(32).toString("base64"))')"
  cat > apps/worker/.dev.vars <<VARS
# AUTO-GENERATED by scripts/docker-dev.sh — local-only, git-ignored.
# Optionals (RESEND_API_KEY, PADDLE_*, ADMIN_EMAILS) are OMITTED, never
# written empty: KEY= is an empty string and flips configured-vs-fallback
# checks. See apps/worker/.dev.vars.example for the full name list.
APP_ENV=local
APP_BASE_URL=http://127.0.0.1:8787
BETTER_AUTH_SECRET=${SECRET}
BETTER_AUTH_URL=http://127.0.0.1:8787
VARS
fi

echo "[dev] applying D1 migrations (local simulator)..."
(cd apps/worker && npx wrangler d1 migrations apply bidmorrow --local)

echo "[dev] starting wrangler dev on :8787 and vite on :5173..."
(cd apps/worker && npx wrangler dev --ip 0.0.0.0 --port 8787) &
WRANGLER_PID=$!
(cd apps/web && npx vite --host 0.0.0.0 --port 5173) &
VITE_PID=$!
trap 'kill "$WRANGLER_PID" "$VITE_PID" 2>/dev/null || true' EXIT
# Exit when either server exits so compose surfaces the failure.
wait -n "$WRANGLER_PID" "$VITE_PID"
